print("Nombre: Leandro Manuel Bolaños Zabala")
print("Edad: 19 años")
print("Fecha de Nacimiento: 2005-03-26")
print("Carrera: Ingenieria en sistemas informaticos")
print("Semestre: IV")
print("Grupo: C force")
print("Proyecto: Estudio de Tatuajes Kraken")
